#!/usr/bin/env python3
"""Build assets/bibs/bibfile.bib from _data/publications.yml (single source of truth).

Run from repo root: python scripts/publications/build.py

Phase 1: YAML → BibTeX. Phase 2 will add ORCID sync into the same file.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path
from typing import Any

import yaml

ROOT = Path(__file__).resolve().parents[2]
PUB_YML = ROOT / "_data" / "publications.yml"
BIB_OUT = ROOT / "assets" / "bibs" / "bibfile.bib"
BIB_HEADER = "% Generated by scripts/publications/build.py — edit _data/publications.yml only.\n\n"

ORCID_DEFAULT = "0000-0002-6954-6859"


def load_publications_data(path: Path) -> dict[str, Any]:
    raw = yaml.safe_load(path.read_text(encoding="utf-8"))
    if raw is None:
        return {"orcid": ORCID_DEFAULT, "publications": []}
    if isinstance(raw, list):
        return migrate_flat_list(raw)
    if "publications" not in raw:
        raw["publications"] = []
    if not raw.get("orcid"):
        raw["orcid"] = ORCID_DEFAULT
    return raw


def migrate_flat_list(entries: list[dict[str, Any]]) -> dict[str, Any]:
    publications = []
    for entry in entries:
        pub = dict(entry)
        pub["id"] = pub.pop("bibkey", pub.get("id", ""))
        paper_url = pub.pop("paper_url", None)
        pub.update(_link_fields_from_url(paper_url))
        pub.setdefault("source", "manual")
        pub.setdefault("show", True)
        publications.append(pub)
    return {"orcid": ORCID_DEFAULT, "publications": publications}


def _link_fields_from_url(paper_url: str | None) -> dict[str, str]:
    if not paper_url:
        return {}
    if "arxiv.org/abs/" in paper_url:
        return {"arxiv": paper_url.rsplit("/abs/", 1)[-1].split("?")[0]}
    if "doi.org/" in paper_url:
        return {"doi": paper_url.rsplit("doi.org/", 1)[-1]}
    return {"url": paper_url}


def paper_url(pub: dict[str, Any]) -> str | None:
    if pub.get("url"):
        return str(pub["url"])
    if pub.get("doi"):
        doi = str(pub["doi"]).removeprefix("https://doi.org/")
        return f"https://doi.org/{doi}"
    if pub.get("arxiv"):
        return f"https://arxiv.org/abs/{pub['arxiv']}"
    return None


def _bib_escape(text: str) -> str:
    return text.replace("{", "\\{").replace("}", "\\}")


def _bib_type(pub_type: str, pub: dict[str, Any]) -> str:
    if pub_type == "thesis":
        venue = (pub.get("journal") or pub.get("venue") or "").lower()
        if "uniandes" in venue:
            return "mastersthesis"
        return "phdthesis"
    return {
        "journal": "article",
        "conf": "inproceedings",
        "preprint": "misc",
    }.get(pub_type, "misc")


def _authors_bib(authors: str) -> str:
    parts = [p.strip() for p in authors.split(",") if p.strip()]
    return " and ".join(parts)


def _school_from_venue(pub: dict[str, Any]) -> str:
    journal = pub.get("journal") or pub.get("venue") or ""
    if "Uniandes" in journal:
        return "Universidad de los Andes"
    if "Trinity" in journal:
        return "Trinity College Dublin"
    return journal


def render_bib_entry(pub: dict[str, Any]) -> str:
    pub_id = pub["id"]
    pub_type = pub.get("type", "misc")
    bib_type = _bib_type(pub_type, pub)
    title = _bib_escape(pub["title"])
    authors = _authors_bib(pub["authors"])
    year = str(pub["year"])
    venue = pub.get("journal") or pub.get("venue") or ""

    lines = [f"@{bib_type}{{{pub_id},"]
    lines.append(f"\ttitle={{{title}}},")
    lines.append(f"\tauthor={{{authors}}},")
    lines.append(f"\tyear={{{year}}},")

    if bib_type == "article":
        lines.append(f"\tjournal={{{_bib_escape(venue)}}},")
    elif bib_type == "inproceedings":
        lines.append(f"\tbooktitle={{{_bib_escape(venue)}}},")
    elif bib_type in ("phdthesis", "mastersthesis"):
        lines.append(f"\tschool={{{_bib_escape(_school_from_venue(pub))}}},")
    elif bib_type == "misc":
        if venue:
            lines.append(f"\thowpublished={{{_bib_escape(venue)}}},")

    if pub.get("doi"):
        doi = str(pub["doi"]).removeprefix("https://doi.org/")
        lines.append(f"\tdoi={{{doi}}},")
    if pub.get("arxiv"):
        lines.append(f"\teprint={{{pub['arxiv']}}},")
        lines.append("\tarchivePrefix={arXiv},")
    link = paper_url(pub)
    if link and not pub.get("doi") and not pub.get("arxiv"):
        lines.append(f"\turl={{{link}}},")
    if pub_id == "poon2026ifogsim":
        lines.append("\tnote={Artifact},")

    if lines[-1].endswith(","):
        lines[-1] = lines[-1][:-1]
    lines.append("}")
    return "\n".join(lines)


def write_bib(publications: list[dict[str, Any]], path: Path) -> None:
    visible = [p for p in publications if p.get("show", True)]
    blocks = [render_bib_entry(p) for p in visible]
    path.write_text(BIB_HEADER + "\n\n".join(blocks) + "\n", encoding="utf-8")


def write_yaml(data: dict[str, Any], path: Path) -> None:
    path.write_text(
        yaml.dump(data, sort_keys=False, allow_unicode=True, width=1000),
        encoding="utf-8",
    )


def main() -> int:
    data = load_publications_data(PUB_YML)
    migrated = isinstance(yaml.safe_load(PUB_YML.read_text(encoding="utf-8")), list)

    write_bib(data["publications"], BIB_OUT)

    if migrated:
        write_yaml(data, PUB_YML)
        print(f"Migrated {PUB_YML.relative_to(ROOT)} to orcid + publications format")

    print(f"Wrote {len([p for p in data['publications'] if p.get('show', True)])} entries to {BIB_OUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
